export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';
export const SET_CURRENT_COORDS = 'SET_CURRENT_COORDS';
export const SET_CURRENT_SERVICE = 'SET_CURRENT_SERVICE';
export const SET_ALL_SERVICES = 'SET_ALL_SERVICES';